Repository wanted-pre-onboarding-fe-team-4/pre-onboarding-9th-3-4, pull requests merged in 2023-03, with the labels that each got.

#3 [#2] 차트를 그리기 위한 데이터 호출 및 정제, 타입 설정
  public/.gitkeep
  public/mock_data.json
  src/App.tsx
  src/api/getData.ts
  src/components/Chart.tsx
  src/types/dataType.ts
  src/utils/convertData.ts
Labels: enhancement

#5 [#4] 차트 구현
  src/components/Chart.tsx
  src/config/ChartStyleConfig.ts
Labels: enhancement

#9 [#8] 필터 구현
  index.html
  public/index.css
  src/App.tsx
  src/api/getData.ts
  src/components/Chart.tsx
  src/components/Chart/index.tsx
  src/components/Chart/style.tsx
  src/components/Chart/tooltip.tsx
  src/components/Filter/index.tsx
  src/components/Filter/type.ts
  src/config/ChartStyleConfig.ts
  src/util/suspendable.ts
  src/utils/convertData.ts
Labels: enhancement

#19 [#12] fix 레전드 컬러 변경을 위해 bar fill 값추가
  src/components/Chart/style.tsx
Labels: bug

#26 [#13] 리드미 작성
  README.md
Labels: documentation
